### PR TITLE
Halfway fixed progress

### PR DESCRIPTION
**Pull request by ciriousjoker**
I pretty much just inserted some example code that should make it work.
It is untested (sorry, I'm really busy), but works in one of my own project just fine.

7za doesnt return a list of extracted files anymore but gets straight to the progress. Example output is in the code.

My code extracts the progress and the file path, but not the file count (super easy, but as I said, I'm busy).

If you have questions, just ask, but I think I "documented" my changes well enough

### CODE REVIEW

**Comment by ciriousjoker** [comment]
Maybe, the -bt switch is necessary for it to work, I forgot to include it in my pull request. This switch "shows time statistics", whatever that means.

**Comment by cchamberlain** [comment]
I haven't used this in a while but if you say it works its good enough for me. Feel free to shoot over another PR if it needs amending (you're doing more testing than me right now).

**Comment by ciriousjoker** [comment]
I hope you checked it before merging, otherwise you're in for a potential adventure ...

What about the notes I included? You read them? Will you implement any of my suggestions?

Anyway, here's a little video of it working:
https://gyazo.com/f8f40b48202aa28e13851b5e263aa227

**Comment by cchamberlain** [comment]
@CiriousJoker I read through the comments on here but this is just a fork of another project I cleaned up in a day (while at a previous employer) and haven't touched since. If your interested in co-maintaining it I'm all for it but I'm afraid I don't have the time for feature development on it atm.

**Comment by ciriousjoker** [comment]
Well me neither ... I just had to write my own little wrapper around the 7zip dlls and had to fix the stdout problem. Then I remembered your solution didnt work so I just threw information at you on how to fix it :D

**Pull request merged**
